### ISSUE TITLE
What is the license of this code?

### ISSUE THREAD

**Issue by neeraj9** [V-Mann-Nick/pgn-pretty-print#2]
I find this an interesting project and want to work together to make this even better. License is required so that I'd know if I can contribute to this or rewrite things from scratch.

**Comment by V-Mann-Nick** [comment]
Yes of course. I never imagined somebody would actually have this kind of interest. I just added one with https://github.com/V-Mann-Nick/pgn-pretty-print/commit/c012bf3ca7ce4b7275e58eb5651575f067b14e2b.

I would be glad to merge any contributions. Thanks for the interest.
